- name: Loop Demo
  hosts: localhost
  tasks:
    - name: Print Fruits
      ansible.builtin.debug:
        msg: "Fruit Name - {{ item }}"
      loop:
        - apple
        - banana
        - orange

# Ansible provide looping with few predefined loop blocks -:
# for (i){
# }    

# {{ item }}