- name: Loop Demo
  hosts: localhost
  tasks:
    - name: Print Fruits
      ansible.builtin.debug:
        msg: "Fruit Name - {{ item }}"
      loop:
        - apple
        - banana
        - orange

    - name: Print Fruits with Quantity
      ansible.builtin.debug:
        msg: "Fruit Name - {{ item.name }}, Quantity - {{ item.quantity }}"
      loop:
        - { name: apple , quantity: 10 }
        - { name: banana , quantity: 20 }
        - { name: orange , quantity: 30 }


# Ansible provide looping with few predefined loop blocks -:
# for (i){
# }    

# {{ item.0 = apple }}
# {{ item.1 = banana }}