# vars in ansbile --> global vars, task related vars , command line vars-----

- name: Demo on vars
  hosts: localhost
  vars:
    URL_PLAY: play.example.com
  tasks:
    - name: Print variable
      ansible.builtin.debug:
        msg: URL_PLAY - {{ URL_PLAY }} 
    - name: Task variable
      ansible.builtin.debug:
        msg: URL_TASK - {{ URL_TASK }} - {{ URL_PLAY }}
      vars:
        URL_TASK: tasks.example.com